### ISSUE TITLE
Naming convention?

### ISSUE THREAD

**Issue by okwolf** [HyperappJS/awesome-hyperapp#34]
I know we are using the `hyperapp-*` prefix for most of these repos, but isn't it customary to use `awesome-*` for other [awesome](https://github.com/sindresorhus/awesome) repos? 🤔

**Comment by zaceno** [comment]
Yeah seems like that's the convention. I'm ok to change it. Although it doesn't seem to matter much (...or?)

**Comment by okwolf** [comment]
@zaceno I'm ok either way. Since we're already changing the name as part of the move to the new org, we should probably settle on a name we can live with for the rest of eternity ⏳

**Comment by zaceno** [comment]
@okwolf yeah ...eternity is a long time 😄 - best not take it lightly! I'm just curious if there are consequences to changing the name. Broken links anywhere?

**Comment by okwolf** [comment]
> @zaceno But I'm thinking ... are there any consequences to changing the name we should consider. Broken links anywhere?

GitHub is smart enough to redirect the [old awesome repo](https://github.com/hyperapp/awesome) to here. Not sure how many renames you can do before it will get lost...

**Comment by zaceno** [comment]
Alright, I'm game. Let's just see if anyone else wants to weigh in (I don't know how long.. 12 hrs?) then let's go for it

**Comment by frenzzy** [comment]
I vote for `awesome-hyperapp` (lowercase) because repo lives on my computer without org prefix :bowtie:

**Comment by okwolf** [comment]
I think `awesome-hyperapp` is also more in line with the title at the top of the page:

> # <img height=24 src=https://cdn.rawgit.com/JorgeBucaran/f53d2c00bafcf36e84ffd862f0dc2950/raw/882f20c970ff7d61aa04d44b92fc3530fa758bc0/Hyperapp.svg> Awesome Hyperapp

**Comment by JorgeBucaran** [comment]
Changed it to `awesome-hyperapp`.
